[tool.poetry]
package-mode = false
description = "practice code for book 'FastAPI: Modern Python Web Development'"
authors = ["Ding Liu <contact@dingliu.me>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
